version: "3.8"

services:
  node_exporter:
    image: "quay.io/prometheus/node-exporter:latest"
    container_name: "node_exporter"
    command:
      - "--path.rootfs=/host"
    ports:
      - "9101:9100"
    pid: "host"
    restart: "unless-stopped"
    volumes:
      - "/:/host:ro,rslave"
