version: "3.2"

services:
  swarm-cronjob:
    image: "crazymax/swarm-cronjob"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Etc/Utc"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "32M"
        reservations:
          cpus: "0.05"
          memory: "32M"
      placement:
        constraints:
          - "node.role == manager"
