version: "3.3"
services:
  universalis-docs:
    image: "ghcr.io/universalis-ffxiv/universalis-docs:latest"
    networks:
      - "net"
      - "traefik-public"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.10"
          memory: "256M"
        reservations:
          cpus: "0.10"
          memory: "256M"
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.universalis-docs-http.rule=Host(`docs.universalis.app`)
        - traefik.http.routers.universalis-docs-http.entrypoints=http
        - traefik.http.routers.universalis-docs-http.middlewares=https-redirect
        - traefik.http.routers.universalis-docs-https.rule=Host(`docs.universalis.app`)
        - traefik.http.routers.universalis-docs-https.entrypoints=https
        - traefik.http.routers.universalis-docs-https.tls=true
        - traefik.http.services.universalis-docs.loadbalancer.server.port=3000
networks:
  net:
    driver: "overlay"
    attachable: true
    driver_opts:
      # Hetzner networks have an MTU of 1400
      com.docker.network.driver.mtu: 1400
  traefik-public:
    external: true
