version: "3.3"
services:
  nginx:
    image: "karashiiro/universalis-nginx:latest"
    depends_on:
      - "universalis"
      - "mariadb"
    networks:
      - "net"
      - "traefik-public"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.30"
          memory: "128M"
        reservations:
          cpus: "0.20"
          memory: "64M"
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.universalis-http.rule=Host(`universalis.app`)
        - traefik.http.routers.universalis-http.entrypoints=http
        - traefik.http.routers.universalis-http.middlewares=https-redirect
        - traefik.http.routers.universalis-https.rule=Host(`universalis.app`)
        - traefik.http.routers.universalis-https.entrypoints=https
        - traefik.http.routers.universalis-https.tls=true
        - traefik.http.routers.universalis-https.tls.certresolver=le
        - traefik.http.services.universalis.loadbalancer.server.port=80
  mogboard:
    image: "ghcr.io/universalis-ffxiv/mogboard-next:latest"
    env_file:
      - "/universalis/mogboard.env"
    networks:
      - "net"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.50"
          memory: "1024M"
        reservations:
          cpus: "0.25"
          memory: "512M"
  mariadb:
    image: "mariadb:10.3.32"
    environment:
      MYSQL_ROOT_PASSWORD: "dalamud"
      MYSQL_DATABASE: "dalamud"
      MYSQL_USER: "dalamud"
      MYSQL_PASSWORD: "dalamud"
    volumes:
      - "/mnt/website-db/mysql:/var/lib/mysql"
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "1024M"
        reservations:
          cpus: "0.25"
          memory: "512M"
      placement:
        constraints:
          - "node.labels.mogboard.db-data == true"
  universalis:
    image: "ghcr.io/universalis-ffxiv/universalis:latest"
    environment:
      ASPNETCORE_URLS: "http://+:4002"
      UNIVERSALIS_POSTGRES_CONNECTION: "Host=postgres;Port=5432;Username=universalis;Password=universalis;Database=universalis;Maximum Pool Size=20;Max Auto Prepare=30"
      UNIVERSALIS_MEMCACHED_CONNECTION: "memcached1,memcached2,memcached3"
    depends_on:
      - "postgres"
      - "memcached1"
      - "memcached2"
      - "memcached3"
    networks:
      - "net"
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "3.70"
          memory: "4096M"
        reservations:
          cpus: "2.00"
          memory: "2048M"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  memcached1:
    image: memcached:1.6.17
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "512M"
        reservations:
          cpus: "0.20"
          memory: "128M"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  memcached2:
    image: memcached:1.6.17
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "512M"
        reservations:
          cpus: "0.20"
          memory: "128M"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  memcached3:
    image: memcached:1.6.17
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "512M"
        reservations:
          cpus: "0.20"
          memory: "128M"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  postgres:
    image: "postgres:14.3"
    environment:
      POSTGRES_USER: "universalis"
      POSTGRES_PASSWORD: "universalis"
    volumes:
      - "/mnt/api-db/data:/var/lib/postgresql/data"
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "1.70"
          memory: "6144M"
        reservations:
          cpus: "1.00"
          memory: "2048M"
      placement:
        constraints:
          - "node.labels.universalis.db-data == true"
networks:
  net:
    driver: "overlay"
    attachable: true
    driver_opts:
      # Hetzner networks have an MTU of 1450
      com.docker.network.driver.mtu: 1450
  traefik-public:
    external: true
