version: "3.3"
services:
  nginx:
    image: "karashiiro/universalis-nginx:latest"
    depends_on:
      - "universalis"
      - "mariadb"
    networks:
      - "net"
      - "traefik-public"
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "0.30"
          memory: "128M"
        reservations:
          cpus: "0.20"
          memory: "64M"
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.universalis-http.rule=Host(`universalis.app`)
        - traefik.http.routers.universalis-http.entrypoints=http
        - traefik.http.routers.universalis-http.middlewares=https-redirect
        - traefik.http.routers.universalis-https.rule=Host(`universalis.app`)
        - traefik.http.routers.universalis-https.entrypoints=https
        - traefik.http.routers.universalis-https.tls=true
        - traefik.http.routers.universalis-https.tls.certresolver=le
        - traefik.http.services.universalis.loadbalancer.server.port=80
  mogboard:
    image: "ghcr.io/universalis-ffxiv/mogboard-next:latest"
    env_file:
      - "/universalis/mogboard.env"
    depends_on:
      - "mariadb"
    networks:
      - "net"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.50"
          memory: "1024M"
        reservations:
          cpus: "0.25"
          memory: "512M"
  mariadb:
    image: "mariadb:10.3.32"
    environment:
      MYSQL_ROOT_PASSWORD: "dalamud"
      MYSQL_DATABASE: "dalamud"
      MYSQL_USER: "dalamud"
      MYSQL_PASSWORD: "dalamud"
    volumes:
      - "/mnt/website-db/mysql:/var/lib/mysql"
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "1024M"
        reservations:
          cpus: "0.25"
          memory: "512M"
      placement:
        constraints:
          - "node.labels.mogboard.db-data == true"
  mariadb-s3sync:
    image: "karashiiro/universalis-s3sync-mariadb:latest"
    environment:
      AWS_SECRET_CSV: "/run/secrets/wasabi_swarm"
      AWS_ENDPOINT: "https://s3.eu-west-1.wasabisys.com"
      AWS_PROFILE: "swarm"
      SYNC_SOURCE: "/dump"
      SYNC_TARGET: "s3://universalis-mogboard-backup"
      REMOTE_MYSQL_ADDR: "mariadb"
      REMOTE_MYSQL_PORT: 3306
      REMOTE_MYSQL_ROOT_PASSWORD: "dalamud"
      REMOTE_MYSQL_DATABASE: "dalamud"
      DUMP_PATH: "/dump/mogboard.sql"
    secrets:
      - "wasabi_swarm"
    volumes:
      - "/mnt/website-db/dump:/dump"
    networks:
      - "net"
    depends_on:
      - "mariadb"
    deploy:
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 0 0 * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: "none"
      placement:
        constraints:
          - "node.labels.mogboard.db-data == true"
  universalis:
    image: "ghcr.io/universalis-ffxiv/universalis:latest"
    environment:
      ASPNETCORE_URLS: "http://+:4002"
      UNIVERSALIS_REDIS_CONNECTION: "65.108.107.235:6379,abortConnect=false"
      UNIVERSALIS_POSTGRES_CONNECTION: "Host=pgbouncer;Port=5432;Username=universalis;Password=universalis;Database=universalis;Read Buffer Size=32768;Maximum Pool Size=100;CommandTimeout=60"
      UNIVERSALIS_MEMCACHED_CONNECTION: "memcached1,memcached2,memcached3"
    depends_on:
      - "rabbitmq"
      - "pgbouncer"
      - "memcached1"
      - "memcached2"
      - "memcached3"
    networks:
      - "net"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "3.70"
          memory: "5120M"
        reservations:
          cpus: "2.00"
          memory: "4096M"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  rabbitmq:
    image: "masstransit/rabbitmq:3.9.15"
    networks:
      - "net"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.50"
          memory: "1024M"
        reservations:
          cpus: "0.30"
          memory: "512M"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  memcached1:
    image: memcached:1.6.17
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "512M"
        reservations:
          cpus: "0.20"
          memory: "128M"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  memcached2:
    image: memcached:1.6.17
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "512M"
        reservations:
          cpus: "0.20"
          memory: "128M"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  memcached3:
    image: memcached:1.6.17
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "512M"
        reservations:
          cpus: "0.20"
          memory: "128M"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  postgres:
    image: "postgres:14.3"
    command: "postgres -c max_connections=200"
    environment:
      POSTGRES_USER: "universalis"
      POSTGRES_PASSWORD: "universalis"
    volumes:
      - "/mnt/api-db/data:/var/lib/postgresql/data"
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "2.70"
          memory: "7168M"
        reservations:
          cpus: "2.00"
          memory: "3072M"
      placement:
        constraints:
          - "node.labels.universalis.db-data == true"
  pgbouncer:
    image: "edoburu/pgbouncer:1.17.0"
    environment:
      AUTH_TYPE: "plain"
      DATABASE_URL: "postgres://universalis:universalis@postgres/universalis"
      DEFAULT_POOL_SIZE: "100"
      MAX_CLIENT_CONN: "550"
      MAX_DB_CONNECTIONS: "190"
      POOL_MODE: "statement"
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: "256M"
        reservations:
          cpus: "0.50"
          memory: "128M"
  postgres-s3sync:
    image: "karashiiro/universalis-s3sync-postgres:latest"
    environment:
      AWS_SECRET_CSV: "/run/secrets/wasabi_swarm"
      AWS_ENDPOINT: "https://s3.eu-west-1.wasabisys.com"
      AWS_PROFILE: "swarm"
      SYNC_SOURCE: "/dump"
      SYNC_TARGET: "s3://universalis-postgres-backup"
      REMOTE_POSTGRES_HOST: "postgres"
      REMOTE_POSTGRES_DATABASE: "universalis"
      REMOTE_POSTGRES_USER: "universalis"
      REMOTE_POSTGRES_PASSWORD: "universalis"
      DUMP_PATH: "/dump/universalis.dump"
    secrets:
      - "wasabi_swarm"
    volumes:
      - "/mnt/api-db/dump:/dump"
    networks:
      - "net"
    depends_on:
      - "postgres"
    deploy:
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 0 0 * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: "none"
      placement:
        constraints:
          - "node.labels.universalis.db-data == true"
networks:
  net:
    driver: "overlay"
    attachable: true
    driver_opts:
      # Hetzner networks have an MTU of 1450
      com.docker.network.driver.mtu: 1450
  traefik-public:
    external: true
secrets:
  wasabi_swarm:
    external: true