version: "3.3"
services:
  nginx:
    image: "karashiiro/universalis-act-nginx:latest"
    networks:
      - "net"
      - "traefik-public"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.07"
          memory: "32M"
        reservations:
          cpus: "0.03"
          memory: "16M"
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.universalis-act-http.rule=Host(`act.universalis.app`)
        - traefik.http.routers.universalis-act-http.entrypoints=http
        - traefik.http.routers.universalis-act-http.middlewares=https-redirect
        - traefik.http.routers.universalis-act-https.rule=Host(`act.universalis.app`)
        - traefik.http.routers.universalis-act-https.entrypoints=https
        - traefik.http.routers.universalis-act-https.tls=true
        - traefik.http.services.universalis-act.loadbalancer.server.port=80
networks:
  net:
    driver: "overlay"
    attachable: true
    driver_opts:
      # Hetzner networks have an MTU of 1400
      com.docker.network.driver.mtu: 1400
  traefik-public:
    external: true
