version: "3.3"
services:
  nginx:
    image: "karashiiro/universalis-nginx:latest"
    depends_on:
      - "universalis"
      - "mariadb"
    networks:
      - "net"
      - "traefik-public"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.20"
          memory: "64M"
        reservations:
          cpus: "0.20"
          memory: "64M"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.universalis-http.rule=Host(`universalis.app`, `staging.universalis.app`)
        - traefik.http.routers.universalis-http.entrypoints=http
        - traefik.http.routers.universalis-http.middlewares=https-redirect
        - traefik.http.routers.universalis-https.rule=Host(`universalis.app`, `staging.universalis.app`)
        - traefik.http.routers.universalis-https.entrypoints=https
        - traefik.http.routers.universalis-https.tls=true
        - traefik.http.routers.universalis-https.tls.certresolver=le
        - traefik.http.services.universalis.loadbalancer.server.port=80
  mogboard:
    image: "ghcr.io/universalis-ffxiv/mogboard-next:latest"
    env_file:
      - "/universalis/mogboard.env"
    depends_on:
      - "mariadb"
    networks:
      - "net"
      - "traefik-public"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.30"
          memory: "512M"
        reservations:
          cpus: "0.30"
          memory: "512M"
  mariadb:
    image: "mariadb:10.3.32"
    environment:
      MYSQL_ROOT_PASSWORD: "dalamud"
      MYSQL_DATABASE: "dalamud"
      MYSQL_USER: "dalamud"
      MYSQL_PASSWORD: "dalamud"
    volumes:
      - "/mnt/website-db/mysql:/var/lib/mysql"
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "512M"
      placement:
        constraints:
          - "node.labels.mogboard.db-data == true"
  mariadb-s3sync:
    image: "karashiiro/universalis-s3sync-mariadb:latest"
    environment:
      AWS_SECRET_CSV: "/run/secrets/wasabi_swarm"
      AWS_ENDPOINT: "https://s3.eu-west-1.wasabisys.com"
      AWS_PROFILE: "swarm"
      SYNC_SOURCE: "/dump"
      SYNC_TARGET: "s3://universalis-mogboard-backup"
      REMOTE_MYSQL_ADDR: "mariadb"
      REMOTE_MYSQL_PORT: 3306
      REMOTE_MYSQL_ROOT_PASSWORD: "dalamud"
      REMOTE_MYSQL_DATABASE: "dalamud"
      DUMP_PATH: "/dump/mogboard.sql"
    secrets:
      - "wasabi_swarm"
    volumes:
      - "/mnt/website-db/dump:/dump"
    networks:
      - "net"
    depends_on:
      - "mariadb"
    deploy:
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 0 0 * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: "none"
      placement:
        constraints:
          - "node.labels.mogboard.db-data == true"
  universalis:
    image: "ghcr.io/universalis-ffxiv/universalis:latest"
    environment:
      ASPNETCORE_URLS: "http://+:4002"
      UNIVERSALIS_MOGBOARD_CONNECTION: "User ID=dalamud;Password=dalamud;Database=dalamud;Server=mariadb;Port=3306"
      UNIVERSALIS_REDIS_CONNECTION: "65.108.107.235:6379,abortConnect=false"
      UNIVERSALIS_REDIS_CACHE_CONNECTION: "cache1:6379,cache2:6379,cache3:6379"
      UNIVERSALIS_SCYLLA_CONNECTION: "10.0.1.7,10.0.1.8"
    depends_on:
      - "mariadb"
      - "rabbitmq"
      - "cache1"
      - "cache2"
      - "cache3"
    networks:
      - "net"
      - "victoria"
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "2.00"
          memory: "2G"
        reservations:
          cpus: "2.00"
          memory: "2G"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  universalis-websocket:
    image: "ghcr.io/universalis-ffxiv/universalis:latest"
    environment:
      ASPNETCORE_URLS: "http://+:4002"
      RECEIVE_STREAMING_EVENTS: "true"
      UNIVERSALIS_MOGBOARD_CONNECTION: "User ID=dalamud;Password=dalamud;Database=dalamud;Server=mariadb;Port=3306"
      UNIVERSALIS_REDIS_CONNECTION: "65.108.107.235:6379,abortConnect=false"
      UNIVERSALIS_REDIS_CACHE_CONNECTION: "cache1:6379,cache2:6379,cache3:6379"
      UNIVERSALIS_SCYLLA_CONNECTION: "10.0.1.7,10.0.1.8"
    healthcheck:
      disable: true
    depends_on:
      - "mariadb"
      - "rabbitmq"
      - "cache1"
      - "cache2"
      - "cache3"
    networks:
      - "net"
      - "victoria"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1.00"
          memory: "1G"
        reservations:
          cpus: "1.00"
          memory: "1G"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  universalis-extra:
    image: "ghcr.io/universalis-ffxiv/universalis:latest"
    environment:
      ASPNETCORE_URLS: "http://+:4002"
      UNIVERSALIS_MOGBOARD_CONNECTION: "User ID=dalamud;Password=dalamud;Database=dalamud;Server=mariadb;Port=3306"
      UNIVERSALIS_REDIS_CONNECTION: "65.108.107.235:6379,abortConnect=false"
      UNIVERSALIS_REDIS_CACHE_CONNECTION: "cache1:6379,cache2:6379,cache3:6379"
      UNIVERSALIS_SCYLLA_CONNECTION: "10.0.1.7,10.0.1.8"
    depends_on:
      - "mariadb"
      - "rabbitmq"
      - "cache1"
      - "cache2"
      - "cache3"
    networks:
      - "net"
      - "victoria"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.50"
          memory: "1G"
        reservations:
          cpus: "0.50"
          memory: "1G"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  universalis-history:
    image: "ghcr.io/universalis-ffxiv/universalis:latest"
    environment:
      ASPNETCORE_URLS: "http://+:4002"
      UNIVERSALIS_MOGBOARD_CONNECTION: "User ID=dalamud;Password=dalamud;Database=dalamud;Server=mariadb;Port=3306"
      UNIVERSALIS_REDIS_CONNECTION: "65.108.107.235:6379,abortConnect=false"
      UNIVERSALIS_REDIS_CACHE_CONNECTION: "cache1:6379,cache2:6379,cache3:6379"
      UNIVERSALIS_SCYLLA_CONNECTION: "10.0.1.7,10.0.1.8"
    depends_on:
      - "mariadb"
      - "rabbitmq"
      - "cache1"
      - "cache2"
      - "cache3"
    networks:
      - "net"
      - "victoria"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1.50"
          memory: "2G"
        reservations:
          cpus: "1.50"
          memory: "2G"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  universalis-upload:
    image: "ghcr.io/universalis-ffxiv/universalis:latest"
    environment:
      ASPNETCORE_URLS: "http://+:4002"
      UNIVERSALIS_MOGBOARD_CONNECTION: "User ID=dalamud;Password=dalamud;Database=dalamud;Server=mariadb;Port=3306"
      UNIVERSALIS_REDIS_CONNECTION: "65.108.107.235:6379,abortConnect=false"
      UNIVERSALIS_REDIS_CACHE_CONNECTION: "cache1:6379,cache2:6379,cache3:6379"
      UNIVERSALIS_SCYLLA_CONNECTION: "10.0.1.7,10.0.1.8"
    depends_on:
      - "mariadb"
      - "rabbitmq"
      - "cache1"
      - "cache2"
      - "cache3"
    networks:
      - "net"
      - "victoria"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "1.50"
          memory: "2G"
        reservations:
          cpus: "1.50"
          memory: "2G"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  universalis-staging:
    image: "ghcr.io/universalis-ffxiv/universalis:latest"
    environment:
      ASPNETCORE_URLS: "http://+:4002"
      UNIVERSALIS_MOGBOARD_CONNECTION: "User ID=dalamud;Password=dalamud;Database=dalamud;Server=mariadb;Port=3306"
      UNIVERSALIS_REDIS_CONNECTION: "65.108.107.235:6379,abortConnect=false"
      UNIVERSALIS_REDIS_CACHE_CONNECTION: "cache-staging1:6379,cache-staging2:6379"
      UNIVERSALIS_SCYLLA_CONNECTION: "10.0.1.7,10.0.1.8"
    depends_on:
      - "mariadb"
      - "rabbitmq"
      - "cache-staging1"
      - "cache-staging2"
    networks:
      - "net"
      - "victoria"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.10"
          memory: "512M"
        reservations:
          cpus: "0.10"
          memory: "512M"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  scylla-lb:
    image: "karashiiro/universalis-scylla-nginx:latest"
    networks:
      - "net"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.30"
          memory: "32M"
        reservations:
          cpus: "0.30"
          memory: "32M"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  rabbitmq:
    image: "masstransit/rabbitmq:3.9.15"
    networks:
      - "net"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "512M"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  cache1:
    image: "redis:7.0.0"
    command: "redis-server --save \"\" --loglevel warning"
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "1G"
        reservations:
          cpus: "0.50"
          memory: "1G"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  cache2:
    image: "redis:7.0.0"
    command: "redis-server --save \"\" --replicaof cache1 6379 --loglevel warning"
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "1G"
        reservations:
          cpus: "0.50"
          memory: "1G"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  cache3:
    image: "redis:7.0.0"
    command: "redis-server --save \"\" --replicaof cache1 6379 --loglevel warning"
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "1G"
        reservations:
          cpus: "0.50"
          memory: "1G"
      placement:
        constraints:
          - "node.labels.cluster.critical != true"
  cache-staging1:
    image: "redis:7.0.0"
    command: "redis-server --save \"\" --loglevel warning"
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "256M"
        reservations:
          cpus: "0.10"
          memory: "256M"
  cache-staging2:
    image: "redis:7.0.0"
    command: "redis-server --save \"\" --replicaof cache-staging1 6379 --loglevel warning"
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "256M"
        reservations:
          cpus: "0.10"
          memory: "256M"
  postgres:
    image: "postgres:14.3"
    command: "postgres -c max_connections=200"
    environment:
      POSTGRES_USER: "universalis"
      POSTGRES_PASSWORD: "universalis"
    volumes:
      - "/mnt/api-db/data:/var/lib/postgresql/data"
    networks:
      - "net"
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "512M"
        reservations:
          cpus: "0.30"
          memory: "512M"
      placement:
        constraints:
          - "node.labels.universalis.db-data == true"
  postgres-s3sync:
    image: "karashiiro/universalis-s3sync-postgres:latest"
    environment:
      AWS_SECRET_CSV: "/run/secrets/wasabi_swarm"
      AWS_ENDPOINT: "https://s3.eu-west-1.wasabisys.com"
      AWS_PROFILE: "swarm"
      SYNC_SOURCE: "/dump"
      SYNC_TARGET: "s3://universalis-postgres-backup"
      REMOTE_POSTGRES_HOST: "postgres"
      REMOTE_POSTGRES_DATABASE: "universalis"
      REMOTE_POSTGRES_USER: "universalis"
      REMOTE_POSTGRES_PASSWORD: "universalis"
      DUMP_PATH: "/dump/universalis.dump"
    secrets:
      - "wasabi_swarm"
    volumes:
      - "/mnt/api-db/dump:/dump"
    networks:
      - "net"
    depends_on:
      - "postgres"
    deploy:
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 0 0 * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: "none"
      placement:
        constraints:
          - "node.labels.universalis.db-data == true"
networks:
  net:
    driver: "overlay"
    attachable: true
    driver_opts:
      # Hetzner networks have an MTU of 1400
      com.docker.network.driver.mtu: 1400
  traefik-public:
    external: true
  victoria:
    external: true
secrets:
  wasabi_swarm:
    external: true