version: "3.9"

services:
  scylla:
    image: "scylladb/scylla:5.1.0"
    cpu_count: 4
    command:
      [
        "--developer-mode",
        "0",
        "--smp",
        "4",
        "--overprovisioned",
        "1",
        "--listen-address",
        "10.0.1.9",
        "--seeds",
        "10.0.1.7,10.0.1.8"
      ]
    privileged: true
    restart: "always"
    network_mode: "host"
    volumes:
      - "/mnt/api-db/scylla:/var/lib/scylla"
