global:
  scrape_interval: "5s"
  scrape_timeout: "5s"
scrape_configs:
- job_name: "Traefik"
  static_configs:
  - targets:
    - "traefik:8080"
- job_name: "Universalis"
  dns_sd_configs:
  - names:
    - "tasks.universalis"
    type: "A"
    port: 4002
- job_name: "Universalis Canary"
  dns_sd_configs:
  - names:
    - "tasks.universalis-canary"
    type: "A"
    port: 4002
- job_name: "cadvisor"
  dns_sd_configs:
  - names:
    - "tasks.cadvisor"
    type: "A"
    port: 8080
