version: "3.5"
services:
  victoria:
    image: "victoriametrics/victoria-metrics:v1.79.5"
    command:
      - "-promscrape.config=/prometheus.yml"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/mnt/metrics-db/victoria:/victoria-metrics-data"
      - "/mnt/metrics-db/victoria-config/prometheus.yml:/prometheus.yml"
    networks:
      - "net"
      - "victoria"
      - "traefik-public"
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: "2G"
        reservations:
          cpus: "2.00"
          memory: "2G"
      placement:
        constraints:
          - "node.role == manager"
          - "node.labels.victoria.victoria-data == true"
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.victoria-http.rule=Host(`victoria.universalis.app`)
        - traefik.http.routers.victoria-http.entrypoints=http
        - traefik.http.routers.victoria-http.middlewares=https-redirect
        - traefik.http.routers.victoria-https.rule=Host(`victoria.universalis.app`)
        - traefik.http.routers.victoria-https.entrypoints=https
        - traefik.http.routers.victoria-https.tls=true
        - traefik.http.services.victoria.loadbalancer.server.port=8428
  cadvisor:
    image: "gcr.io/cadvisor/cadvisor:v0.46.0"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker:/var/lib/docker:ro"
      - "/dev/disk:/dev/disk:ro"
    networks:
      - "net"
      - "victoria"
    deploy:
      mode: "global"
      resources:
        limits:
          cpus: "0.20"
          memory: "256M"
        reservations:
          cpus: "0.10"
          memory: "128M"
  tempo:
    image: "grafana/tempo:latest"
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - "/monitoring/tempo/tempo.yaml:/etc/tempo.yaml:ro"
      - "/monitoring/tempo/data/:/tmp/tempo:rw"
    networks:
      - "net"
      - "victoria"
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: "4G"
        reservations:
          cpus: "0.50"
          memory: "4G"
      placement:
        constraints:
          - "node.labels.monitoring.data == true"
  otel-collector:
    image: "otel/opentelemetry-collector:0.69.0"
    command: [ "--config=/etc/otel-collector.yaml" ]
    networks:
      - "net"
      - "victoria"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "1G"
        reservations:
          cpus: "0.50"
          memory: "1G"
    configs:
      - source: otel_collector
        target: /etc/otel-collector.yaml
  grafana:
    image: "grafana/grafana:9.1.0"
    environment:
      GF_SERVER_DOMAIN: "monitor.universalis.app"
      GF_DEFAULT_FORCE_MIGRATION: "true"
    volumes:
      - "/mnt/metrics-db/grafana:/var/lib/grafana"
      - "/mnt/metrics-db/grafana-config/grafana.ini:/etc/grafana/grafana.ini"
    networks:
      - "net"
      - "traefik-public"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "128M"
        reservations:
          cpus: "0.15"
          memory: "64M"
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.grafana-http.rule=Host(`monitor.universalis.app`)
        - traefik.http.routers.grafana-http.entrypoints=http
        - traefik.http.routers.grafana-http.middlewares=https-redirect
        - traefik.http.routers.grafana-https.rule=Host(`monitor.universalis.app`)
        - traefik.http.routers.grafana-https.entrypoints=https
        - traefik.http.routers.grafana-https.tls=true
        - traefik.http.services.grafana.loadbalancer.server.port=3000
      placement:
        constraints:
          - "node.labels.grafana.grafana-data == true"
networks:
  net:
    driver: "overlay"
    attachable: true
    driver_opts:
      # Hetzner networks have an MTU of 1400.
      com.docker.network.driver.mtu: 1400
  victoria:
    external: true
  traefik-public:
    external: true
configs:
  otel_collector:
    external: true
