global:
  scrape_interval: "5s"
  scrape_timeout: "5s"
scrape_configs:
  - job_name: "PostgreSQL"
    static_configs:
      - targets:
          - "postgres-exporter:9187"
  - job_name: "Tempo"
    static_configs:
      - targets:
          - "tempo:3200"
  - job_name: "ScyllaDB 1"
    static_configs:
      - targets:
          - "10.0.1.7:9180"
  - job_name: "ScyllaDB 2"
    static_configs:
      - targets:
          - "10.0.1.8:9180"
  - job_name: "ScyllaDB 3"
    static_configs:
      - targets:
          - "10.0.1.9:9180"
  - job_name: "Redis Master"
    static_configs:
      - targets:
          - "65.108.107.235:9121"
  - job_name: "Redis Replica"
    static_configs:
      - targets:
          - "65.108.107.235:9122"
  - job_name: "Traefik"
    dns_sd_configs:
      - names:
          - "tasks.traefik"
        type: "A"
        port: 8080
  - job_name: "RabbitMQ"
    dns_sd_configs:
      - names:
          - "tasks.rabbitmq"
        type: "A"
        port: 15692
  - job_name: "Universalis"
    dns_sd_configs:
      - names:
          - "tasks.universalis"
        type: "A"
        port: 4002
  - job_name: "Universalis Upload"
    dns_sd_configs:
      - names:
          - "tasks.universalis-upload"
        type: "A"
        port: 4002
  - job_name: "Universalis History"
    dns_sd_configs:
      - names:
          - "tasks.universalis-history"
        type: "A"
        port: 4002
  - job_name: "Universalis Extra"
    dns_sd_configs:
      - names:
          - "tasks.universalis-extra"
        type: "A"
        port: 4002
  - job_name: "Universalis WebSocket"
    dns_sd_configs:
      - names:
          - "tasks.universalis-websocket"
        type: "A"
        port: 4002
  - job_name: "Universalis Reserve"
    dns_sd_configs:
      - names:
          - "tasks.universalis-reserve"
        type: "A"
        port: 4002
  - job_name: "Universalis Staging"
    dns_sd_configs:
      - names:
          - "tasks.universalis-staging"
        type: "A"
        port: 4002
  - job_name: "Universalis Canary"
    dns_sd_configs:
      - names:
          - "tasks.universalis-canary"
        type: "A"
        port: 4002
  - job_name: "cadvisor"
    dns_sd_configs:
      - names:
          - "tasks.cadvisor"
        type: "A"
        port: 8080
  - job_name: "Mogboard Alerts"
    dns_sd_configs:
      - names:
          - "tasks.mogboard-alerts"
        type: "A"
        port: 9000
  - job_name: "node"
    static_configs:
      - targets:
          - "65.108.107.235:9100"
          - "10.0.1.1:9100"
          - "10.0.1.2:9100"
          - "10.0.1.3:9100"
          - "10.0.1.4:9100"
          - "10.0.1.5:9100"
          - "10.0.1.6:9100"
          - "10.0.1.7:9101"
          - "10.0.1.8:9101"
          - "10.0.1.9:9101"
          - "10.0.1.10:9100"
          - "10.0.200.2:9100"
