version: "2.4"
services:
  redis:
    image: "redis:7.0.0"
    command:
      - "redis-server"
      - "--port"
      - "6380"
      - "--save"
      - "300" # Save every 5 minutes
      - "1"
      - "--replicaof"
      - "127.0.0.1"
      - "6379"
      - "--hash-max-listpack-value"
      - "128"
      - "--zset-max-listpack-value"
      - "40000"
      - "--loglevel"
      - "warning"
    network_mode: "host"
    volumes:
      - "/home/universalis/db/data:/data:rw"
  exporter:
    image: "oliver006/redis_exporter:v1.45.0"
    network_mode: "host"
    environment:
      REDIS_ADDR: "redis://localhost:6380"
      REDIS_EXPORTER_WEB_LISTEN_ADDRESS: "0.0.0.0:9122"
