#cloud-config
write_files:
  - encoding: "b64"
    content: ${docker_compose}
    owner: "root:root"
    path: "/app/docker-compose.yml"
    permissions: "0644"
  - encoding: "b64"
    content: ${sqlinit}
    owner: "root:root"
    path: "/app/sqlinit.tar"
    permissions: "0644"
runcmd:
  - "mkdir -p /mnt/mogboard-db"
  - "mount -o discard,defaults /dev/disk/by-id/scsi-0HC_Volume_${volume_id} /mnt/mogboard-db"
  - "mkdir -p /mnt/mogboard-db/mariadb"
  - "mkdir -p /mnt/mogboard-db/mariadb-dump"
  - "mkdir -p /mnt/mogboard-db/mariadb-import"
  - "cd /app && tar xvf sqlinit.tar"
  - "cd /app && docker compose up -d"